#ifndef _CONFIG_H_
#define _CONFIG_H_ 

#define SCHEDULER_MAX_EVENT_SIZE MAX(APP_TIMER_SCHED_EVT_SIZE, BLE_STACK_HANDLER_SCHED_EVT_SIZE)
#define SCHEDULER_QUEUE_SIZE    10

#define TIMER_PRESCALER                 0
#define TIMER_MAX_TIMERS                4       
#define TIMER_OP_QUEUE_SIZE             5      

#define TOGGLE_LED_GPIOTE_CHANNEL       0

#define MAIN_BUTTON_PIN BUTTON_0
#define MAIN_LED_PIN    LED_0

#define SECONDARY_BUTTON_PIN BUTTON_1
#define SECONDARY_LED_PIN    LED_1


// BLE related
#define BLE_DEVICE_NAME "yhb-ble"
#define BLE_MANUFECTURE_NAME "hongbo@yang.me"
#define BLE_MODEL_NUM "ble1"
#define BLE_DEVICE_DEFAULT_TX_POWER -30

// BLE gap related
#define BLE_CONN_MIN_INTERVAL 80 // 80 * 1.25 ms = 100 ms
#define BLE_CONN_MAX_INTERVAL 800 // 800 * 1.25ms = 1 s //BLE_GAP_CP_MAX_CONN_INTVL_MAX
#define BLE_CONN_SLAVE_LANTENCY 0
#define BLE_CONN_SUPERVISION_TIMEOUT 100

#define BLE_ADVERTISED_SERVICE_UUID_16BIT 0x1804

#endif // _CONFIG_H_

